### ISSUE TITLE
Support third-party dependencies for JVM tools

### ISSUE THREAD

**Issue by yykamei** [sider/runners#1000]
According to the [document](https://checkstyle.sourceforge.io/config.html), Checkstyle can get written arbitrary modules in its configuration.

Some of our customers want its feature, but I'm not sure how to implement it.

**Comment by ybiquitous** [comment]
Perhaps, I think we can do it by setting the `CLASSPATH` environment variable.

**Comment by ybiquitous** [comment]
E.g.

```yaml
linter:
  checkstyle:
    classpath:
      - custom-rules/*
      - https://foo/custom-rules.jar # ???
```

**Comment by yykamei** [comment]
Also, it might be better to support build tools, such as Gradle.

**Comment by ybiquitous** [comment]
Oh, I don't want to support Maven or Gradle until we will really need them...
The implementations and test cases would be too complex.

**Comment by ybiquitous** [comment]
I found the document for specifying classpath:
https://checkstyle.sourceforge.io/cmdline.html#Usage_by_Classpath_update

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/473530/80178504-55440380-8639-11ea-8005-cd2898ceb685.png">

**Comment by ybiquitous** [comment]
We need to consider:

- a new option that can support all Java and JVM tools (also Kotlin)
- a new option that can download JAR files from the network.
- what the standard format is, e.g. Maven? (`linter.*.maven` like `linter.*.gems`)

**Comment by ybiquitous** [comment]
One suggestion:

```yaml
linter:
  checkstyle:
    # Download from the maven repository
    maven:
      # short version (like Gradle format) - {groupId}:{artifactId}:{version}
      - org.wildfly.checkstyle:wildfly-checkstyle-config:1.0.8.Final
      # long version
      - groupId: org.wildfly.checkstyle
        artifactId: wildfly-checkstyle-config
        version: 1.0.8.Final

    # Set `CLASSPATH`
    classpath:
      # relative path
      - custom-rules/foo.jar
      # glob
      - "custom-rules/**/*.jar"
      # remote (e.g. via `curl`)
      - https://foo.com/custom-rules.jar
```
