### ISSUE TITLE
[Misspell] Support list format for `ignore` option

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#1071]
The `ignore` option should be a comma-separated list, e.g. `center,behavior`.
I believe more useful if it would support also a list format:

```yaml
linter:
  misspell:
    ignore: [center, behavior]
    # or
    ignore:
      - center
      - behavior
```

https://github.com/sider/runners/blob/8d9cec16b78ddfcd6f7f6c3f9c9cb0f67c843aeb/lib/runners/processor/misspell.rb#L10
