### ISSUE TITLE
[PMD CPD] Analyze multiple languages by default

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#1181]
Currently, users can specify only one language via `sider.yml` (default: `java`).
This is not useful, so I think it's better to analyze multiple languages by default.

https://github.com/sider/runners/blob/01fae1b32766810284c23092970aabb2e8326971/lib/runners/processor/pmd_cpd.rb#L10

**Comment by suetsuguk** [comment]
@ybiquitous @yykamei 
I'm thinking about the configuration format. There are possible two candidates.

As for Conf. A. bellow, the `language` option accepts an array of languages.
It is so simple that we can implement easily. But, users may want to apply different values for other options (minimum-tokens, etc.) for each language.

As for Conf. B., we provide an array of a hash of options. The `language` option for each hash also accepts an array of languages.
We can provide highly flexible configuration. But, the source code can be complicated. I actually do not know how to create this data structure by using the `Schema::BaseConfig` class.

Since Conf. B. covers Conf. A., I would like to choose Conf. A. as a first step. We will revisit Conf. B. in the future instead.

What do you think?


Conf. A.
```yaml
linter:
  pmd_cpd:
    language: [c, java, ruby]
    minimum-tokens: 70
    files: src
    encoding: UTF-8
    skip-duplicate-files: true
    non-recursive: true
    skip-lexical-errors: true
    ignore-annotations: true
    ignore-identifiers: true
    ignore-literals: true
    ignore-usings: true
    no-skip-blocks: true
    skip-blocks-pattern: "#ifdef TEST|#endif"

```
Conf. B.
```yaml
linter:
  pmd_cpd:
    - language: [java, jsp]
      minimum-tokens: 100
      files: src/java
      encoding: UTF-8
      skip-duplicate-files: true
      non-recursive: true
      skip-lexical-errors: true
      ignore-annotations: true
      ignore-identifiers: true
      ignore-literals: true
    - language: c
      minimum-tokens: 70
      files: src/c
      encoding: ASCII
      no-skip-blocks: true
      skip-blocks-pattern: "#ifdef TEST|#endif"
    - language: cs
      minimum-tokens: 50
      files: src/c_sharp
      encoding: UTF-8
      ignore-usings: true
```

**Comment by ybiquitous** [comment]
@suetsuguk Thanks for the explanation. Let's consider actual use-cases, for example.

## Use-case 1: Just analyze multi-languages

```yaml
linter:
  pmd_cpd:
    language: [ruby, go, ecmascript]
```

## Use-case 2: Analyze multi-languages but different locations

```yaml
linter:
  pmd_cpd:
    - language: [ruby, go]
      src: backend
    - language: [ecmascript]
      src: frontend
```

---

Is the use-case 2 needless to consider?
