### ISSUE TITLE
Allow multiple `root_dir`

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#1286]
Currently, the `root_dir` option in `sider.yml` support a single value:

```yaml
linter:
  goodcheck:
    root_dir: src/
```

But, if users could specify multiple `root_dir` for monorepo projects, it would be so useful:

```yaml
linter:
  goodcheck:
    root_dir:
      - backend/
      - frontend/
      # - and so on...
```

**Comment by ybiquitous** [comment]
One question: should we consider the following situation?

```yaml
linter:
  goodcheck:
    - root_dir: backend/
      config: backend_goodcheck.yml
    - root_dir: frontend/
      config: frontend_goodcheck.yml
```
