### ISSUE TITLE
[Checkstyle] Localization support

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#1658]
See https://checkstyle.org/config_system_properties.html#Localisation_Support

https://github.com/checkstyle/checkstyle/tree/432bafd49ed9d801f44a04ad710cc9372538e588/src/main/resources/com/puppycrawl/tools/checkstyle/checks/sizes

Via `checkstyle.xml`:

```xml
<property name="checkstyle.locale.language" value="ja"/>
<property name="checkstyle.locale.country" value="JP"/>
```

Via `sider.yml`:

```yaml
linter:
  checkstyle:
    locale:
      language: ja
      country: JP
```
