### ISSUE TITLE
Specify npm packages in sider.yml

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#1689]
It may be useful for users who **don't** want to manage npm packages used for analysis in their `package.json` (like the `linter.rubocop.gems` option).
In most cases, analysis tools (linters) are not necessary for users' projects at runtime.

Pros:

- Not big `package.json` and `package-lock.json` (or `yarn.lock`)
- Faster `npm install` 
- Fewer dependencies hell

Cons:

- Must edit `sider.yml`

Here is an example of `sider.yml`:

```yaml
linter:
  eslint:
    npm:
      - eslint # alias to `eslint@latest`
      - eslint-plugin-react@<11 # short of `{ name: eslint-plugin-react, version: "<11" }`
      - { name: eslint-plugin-node, version: 11.1.2 } # long
      - { name: eslint-foo, version: "mochajs/mocha#4727d357ea" # GitHub URL
```

According to `dependencies` of `package.json`, see:
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies
