### ISSUE TITLE
[Cppcheck] Support options for suppression

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#1748]
Cppcheck [provides some ways to suppress issues](https://github.com/danmar/cppcheck/blob/bf951ea5e65a6f03af23319f2ffd7e8e51eb2a98/man/manual.md#suppressions):

- via command line
- via suppression file (`.txt` or `.xml`)
- via inline comment

I think the suppression feature is useful in some case, so I suggest our supporting way as follows:

```yaml
# sider.yml
linter:
  cppcheck:
    suppress:
      - memleak:src/file1.cpp
      - uninitvar
    suppressions-list: suppressions.txt
```

adding the following options

- `linter.cppcheck.suppress` (`string[]`, optional, default to `[]`)
- `linter.cppcheck.suppressions-list` (`string`, optional, default to `nil`)

NOTE: I think XML support is not necessary for now.
