### ISSUE TITLE
Introduce common options

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#2096]
I think we can make `sider.yml` more user-friendly by introducing common option names.

For example, the stylelint runner supports the `glob` option for analyzed files, on the other hand, the ESLint runner supports the `target` option (previously `dir`).

https://github.com/sider/runners/blob/90a9a49e96fdee49cf74895df8784d618205fb16/lib/runners/processor/stylelint.rb#L16

https://github.com/sider/runners/blob/90a9a49e96fdee49cf74895df8784d618205fb16/lib/runners/processor/eslint.rb#L10-L11

I suggest the following options for common:

- `linter.{id}.target`: files or directories to analyze
- `linter.{id}.dependencies`: e.g. `gems` or `jvm_deps`

For example:

```yaml
linter:
  rubocop:
    target: src/**/*.rb
    dependencies:
      - { name: rubocop-rails, version: 1.2.3 }
  checkstyle:
    target: src/
    dependencies:
      - { name: "com.github.sevntu-checkstyle:sevntu-checks", version: 1.37.1 }
```
