### ISSUE TITLE
Support `linter.<id>.dependencies` for Python tools

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#2262]
We have added the common option `linter.<id>.dependencies` via #2202. This option also should be able to be applied to `linter.flake8.plugins`:

https://github.com/sider/runners/blob/ca5466599d4ef09486c270d6ad58095fdcdc7ad8/lib/runners/processor/flake8.rb#L12

https://github.com/sider/runners/blob/ca5466599d4ef09486c270d6ad58095fdcdc7ad8/lib/runners/processor/flake8.rb#L28-L32

Suggestion (for example):

```yaml
linter:
  flake8:
    dependencies:
      - flake8-bandit
      - flake8-builtins==1.4.1
      - { name: "flake8-docstrings", version: ">=1.4.0" }
```

- Install dependencies via the `pip install` command. See below:
  https://github.com/sider/runners/blob/ca5466599d4ef09486c270d6ad58095fdcdc7ad8/lib/runners/python.rb#L13
