### ISSUE TITLE
Add `ignore` option for Secret Scan

### ISSUE THREAD

**Issue by gnakagaw** [sider/runners#2766]
[Secret Scan](https://help.sider.review/tools/others/secret-scan/) often makes false positive detection. It's unavoidable for several cases because the scanning is regex based. 

It's useful to make a ignoring option not for all tools but only for secret scanning.

Example
```
linter:
  secret_scan:
    ignore:
        - "public/assets/webpack/**"
```
