### ISSUE TITLE
Deprecate `linter.*.options` option

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#368]
The following is an example of ESLint.

This format of `sider.yml` is deprecated.

```yaml
# sider.yml
linter:
  eslint:
    options:
      dir: src/
```

https://github.com/sider/runners/blob/e8105085f0d76e2b45f3c8e914dee7d2ff0582e7/lib/runners/processor/eslint.rb#L16-L27

It is not described in the current documentation:
https://help.sider.review/tools/javascript/eslint#configuration-via-sideryml

## Suggestion

1. Show deprecated warnings.
2. Announce the end day to users.
3. Drop support.
