### ISSUE TITLE
Add links to issues of custom rule analyzers

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#674]
Currently, the following custom rule analyzers have no `links` within their issues:

- Goodcheck
- Phinder
- Querly
- TyScan

I think so useful if the analyzers can have `links` for issues.

Assuming that you have a `goodcheck.yml`:

```yaml
rules:
  id: sample_rule
  pattern: foo
  message: Disallow `foo`
```

Then, the links would be:

```
["https://github.com/your/repo/blob/1eed7bb88508a9b39ca4ec7bdb467f7fe81e3382/goodcheck.yml#L2"]
```

Users could jump to the specific `goodcheck.yml` position and see the rule's details.
