### ISSUE TITLE
Support shortcut format for `gems` option

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#757]
## Example

```yaml
# sider.yml
linter:
  rubocop:
    gems:
      - "rubocop:0.72.0"
      - "rubocop-rspec:~>1.38"
```

## See also

- https://help.sider.review/getting-started/custom-configuration#gems-option
- https://github.com/rubygems/rubygems/blob/18b377976e7d337bb53bba4960b607f6e024dd71/lib/rubygems/command.rb#L199-L204
- https://github.com/rubygems/rubygems/blob/db90c7a909b40be8a4b0431fb8c886476ef7e6af/lib/rubygems/requirement.rb#L14-L27
