### ISSUE TITLE
[ESLint] `root_dir` and `dir` options are confusing

### ISSUE THREAD

**Issue by ybiquitous** [sider/runners#891]
`root_dir` and `dir` are confusing and I think users can easily misconfigure `sider.yml`.

E.g.

```yaml
linter:
  eslint:
    root_dir: frontend/
    dir: frontend/src/
```

So, I suggest:

- Mark `linter.eslint.dir` option as **deprecated**
- Add `linter.eslint.target` option

See also:

https://github.com/sider/runners/blob/1d1e1253e177b860ffdeb62d1573de6e835a2474/lib/runners/processor/eslint.rb#L8
